### ISSUE TITLE
Package Count

### ISSUE THREAD

**Issue by leopapadopoulos6** [clamsfeel2/nitchplusplus#1]
Hello, not sure how to do one of these, but for me the package count was always showing -1 and 'unsupported distribution' until I changed it to:

`SystemInfo::distroID == "\"endeavouros\""`

Simple mistake, but I believe it was (literally) comparing:
"endeavouros" == endeavouros

so I used the backslash for the double quote confusion. Hopefully helps someone. Looks really clean though. I got nitch then saw this right after and gave it a shot too since the former is no longer maintained.

**Comment by clamsfeel2** [comment]
I’ve added logic to handle leading and trailing double quotes around the ID in the os-release file. This change seems to have resolved the issue on my end. You can check the details of the update in this commit: [a1a09ac](https://github.com/clamsfeel2/nitchplusplus/commit/a1a09ac7a705b43996c14873af8092f5c638bf79).

Could you please test it on your side and let me know if it fixes the issue for you as well? Also, I wasn't able to reproduce the problem with nitch++ --distro [distro name], so if you continue to encounter that issue, please let me know.
